channels:
  - conda-forge
  - hdsr-mid
dependencies:
  - python>=3.8,<=3.12
  - path-finder  # on conda channel hdsr-mid
  - lxml
  - isort  # only required for auto-format code
  - black  # only required for auto-format code
  - pytest  # only required for running tests
  - pytest-cov  # only required for running tests coverage

